# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SenseCap tracker T1000-A add-on
version: "1.2.0"
slug: sensecap-tracker
description: SenseCap tracker T1000-A add-on
url: "https://github.com/oleksiyp/sensecap-tracker/tree/main/senscap-tracker"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/oleksiyp/{arch}-sensecap-tracker-addon"
